name: demo_app
description: "Demo App"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

  # STATE MANAGEMENT
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  # SERVICE LOCATOR
  get_it: ^8.0.3

  # NAVIGATION
  go_router: ^15.1.1

  # NETWORK
  dio: ^5.7.0

  # LOG
  talker: ^4.6.11
  talker_dio_logger: ^4.6.11
  talker_bloc_logger: ^4.6.11

  # FILE
  mime: ^2.0.0
  path_provider: ^2.1.5

  equatable: ^2.0.7
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  diacritic: ^0.1.6
  flutter_animate: ^4.5.2
  image: ^4.5.4
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^2.7.5
  build_runner: ^2.4.15
  build_verify: ^3.1.0


flutter:
  assets:
    - assets/

  uses-material-design: true
